const products = [
  {
    _id: "1",
    name: "Airpods",
    image: "/images/airpods.jpg",
    description: "Wireless earbuds for an amazing listening experience.",
    brand: "Apple",
    category: "Electronics",
    price: 199.99,
    countInStock: 50,
    rating: 4.5,
    numReviews: 120,
  },
  {
    _id: "2",
    name: "Alexa",
    image: "/images/alexa.jpg",
    description: "A smart assistant to help you manage your tasks.",
    brand: "Amazon",
    category: "Smart Home",
    price: 99.99,
    countInStock: 30,
    rating: 4.2,
    numReviews: 80,
  },
  {
    _id: "3",
    name: "Camera",
    image: "/images/camera.jpg",
    description: "High-quality camera for capturing precious moments.",
    brand: "Canon",
    category: "Photography",
    price: 599.99,
    countInStock: 20,
    rating: 4.8,
    numReviews: 150,
  },
  {
    _id: "4",
    name: "Mouse",
    image: "/images/mouse.jpg",
    description: "Ergonomic mouse for comfortable computer navigation.",
    brand: "Logitech",
    category: "Computer Accessories",
    price: 29.99,
    countInStock: 100,
    rating: 4.0,
    numReviews: 50,
  },
  {
    _id: "5",
    name: "Playstation",
    image: "/images/playstation.jpg",
    description: "Gaming console for immersive gaming experiences.",
    brand: "Sony",
    category: "Gaming",
    price: 399.99,
    countInStock: 10,
    rating: 4.7,
    numReviews: 200,
  },
  {
    _id: "6",
    name: "Phone",
    image: "/images/phone.jpg",
    description:
      "Feature-packed smartphone for communication and entertainment.",
    brand: "Samsung",
    category: "Electronics",
    price: 699.99,
    countInStock: 25,
    rating: 4.6,
    numReviews: 180,
  },
];
export default products;
